story/cord 11
diging/cord19-geo-explorer pull request #11
Opened 2020-06-30 17:38 UTC by coder-aakash994

2020-07-01 17:40 UTC, jdamerow commented
Jenkins, test this please.

2020-07-01 17:47 UTC, jdamerow requested changes

2020-07-01 17:47 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/paper.html
> +	      	$("#[(${#ids.next('para')})]").mark("[(${match.locationName})]", { "separateWordSearch": false}).attr('title', title);
the title should be the title of the found match, not the publication title

2020-07-06 21:38 UTC, coder-aakash994 commented
not sure if this is this is correct as this shows the location instead of a title.

2020-07-07 19:37 UTC, jdamerow commented
Jenkins, test this please.

2020-07-07 20:04 UTC, jdamerow commented
Looks good I think. let's make that a link though that links to the wikipedia article in a new tab (for the url, basically just the wikipedia url prefix + the term should do it )

2020-07-08 22:38 UTC, coder-aakash994 commented
(for the url, basically just the wikipedia url prefix + the term should do it ) can you elaborate? I am unable to figure out the wiki url prefix variable and the term that needs to be appended.  I have implemented anchor tag to open a new page on the matched paragraph.

2020-07-10 18:47 UTC, jdamerow commented
Something is going wrong. It turns the whole paragraph into a link and the hover text is wrong (in the page in the screenshot, it says "Italy" for Wuhan).
![image](https://user-images.githubusercontent.com/8881141/87188165-57267600-c2bc-11ea-8902-742ada266f95.png)

2020-07-16 22:28 UTC, closed without merging