Story/cord 11
diging/cord19-geo-explorer pull request #18
Opened 2020-07-16 22:31 UTC by coder-aakash994

On the paper page, when hovering over a found location in the text the wikipedia title should be shown

2020-07-16 22:35 UTC, coder-aakash994 commented
I was able to wrap the element correctly but the url issue(opening the same wiki title for all links) still persists. I checked the javascript code generated in the page source and looks like the final script is replacing all the hrefs in the previous paragraphs. I tried multiple things to fix this but I am unable to. 

One fix involved using the attr function to attach the url but although the url issue gets solved, the entire paragraph gets wrapped in the anchor again.

2020-07-17 14:14 UTC, jdamerow requested changes

2020-07-17 14:14 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/paper.html
> +	        $( "mark" ).wrap( "<a href='https://en.wikipedia.org/wiki/"+title+"' target=_blank></a>" );
have you tried adding a span with a class that contains for example the index of the loop and use javascript to generate the link on click. something like this:
```
$("#[(${#ids.next('para')})]").mark("[(${match.locationName})]", { "separateWordSearch": false, "className": "wiki-[(${stats.index})]"})
$("mark.wiki-[(${stats.index})]).click(...)
```
does this make sense? this is about iterations in thymeleaf: https://www.baeldung.com/thymeleaf-iteration, and this is the mark.js documentation: https://markjs.io/

2020-07-23 18:33 UTC, jdamerow commented
Jenkins, test this please.

2020-07-23 18:42 UTC, jdamerow requested changes

2020-07-23 18:42 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/paper.html
> +	        $("#[(${#ids.next('para')})]").mark("[(${match.locationName})]", { "separateWordSearch": false, "className": "wiki-[(${#ids.next('para')})]-[(${iStat.index})]"})
you are marking the text 3 times resulting in 3 divs around the text. One should be enough

2020-07-24 14:45 UTC, jdamerow commented
Jenkins, test this please.

2020-07-24 14:57 UTC, merged