[CORD-31] Story/ cord 31
diging/cord19-geo-explorer pull request #28
Opened 2020-09-04 16:01 UTC by coder-aakash994

App version needs to be shown in footer

2020-09-04 20:33 UTC, jdamerow requested changes
the footer insert needs to go into the layout not in every individual page

2020-09-04 20:33 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/layouts/footer.html
> +	<div th:fragment="footer" th:align="center">Cord19 Explorer version 2.0</div>
this needs to pull the version from the pom (similar to other apps like conceptpower).

2020-09-21 18:16 UTC, jdamerow requested changes
The individual pages should not have the footer insert. That should be done in the layout.

2020-09-23 17:18 UTC, coder-aakash994 commented
I have moved the footer and navbar insert to main.html. The individual pages do not have the footer insert anymore

2020-09-25 09:48 UTC, closed without merging