Story/cord 31
diging/cord19-geo-explorer pull request #31
Opened 2020-09-25 09:48 UTC by coder-aakash994

add footer to layout

2020-09-25 13:38 UTC, jdamerow commented
Let's talk about this. There are still 30 changed files.

2020-10-09 15:13 UTC, jdamerow requested changes

2020-10-09 15:13 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/layouts/footer.html
> +						th:text="${#strings.defaultString(@environment.getProperty('pullrequest'),'')}"></span>
pullrequest and buildNumber need to be properties in the pom.xml

2020-10-09 15:14 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-09 15:34 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/layouts/footer.html
> +					<span th:if="${@environment.getProperty('pullReq') != null}">,
that should be `pullrequest`

2020-10-09 15:34 UTC, jdamerow commented on cord19-explorer/src/main/webapp/WEB-INF/views/layouts/footer.html
> +						th:text="${#strings.defaultString(@environment.getProperty('pullrequest'),'')}"></span>
never mind

2020-10-09 15:34 UTC, jdamerow commented
I believe you need to add the build number plugin to get buildnumbers. Do you get any locally?

2020-10-14 15:40 UTC, coder-aakash994 commented
The build number plugin is already present in the pom.xml.

2020-10-23 20:17 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-23 20:37 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-23 20:42 UTC, jdamerow commented
Hm, I'm not getting a version number. Do they get generated locally?

2020-10-28 17:16 UTC, coder-aakash994 commented
The config.properties were missing the buildNum and pullReq fields. The version info isn't null but it still is empty in my local.

2020-11-02 15:29 UTC, jdamerow commented
Seems to work great on staging! 👍
![image](https://user-images.githubusercontent.com/8881141/97886175-45972d00-1cf6-11eb-8d4a-907ad69be4d9.png)

2020-11-02 15:29 UTC, merged